version: "3.4"

services:
  dr_doom:
    build:
      context: ./dr-doom
    ports:
      - "8000:8000"
  ultron:
    build:
      context: ./ultron
    ports:
      - "3000:3000"
    command: yarn dev
